# Generated by Django 6.0.1 on 2026-02-03 12:10

import django.db.models.deletion
import movie_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')])),
                ('brith_day', models.DateField()),
                ('profile_picture', models.ImageField(upload_to=movie_app.models.actor_directory_path)),
            ],
            options={
                'ordering': ['first_name', '-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['first_name', '-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_choice', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['genre_choice'],
            },
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The official name of the studio.', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Do not use < > : " / \\ | ? * #, %, &, {, }, $, !, +, or emojis', max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('qulity', models.CharField(choices=[('HD', 'HD'), ('Cam', 'Cam')], default='HD')),
                ('poster', models.ImageField(upload_to=movie_app.models.poster_directory_path)),
                ('backdrop1', models.ImageField(upload_to=movie_app.models.backdrop_directory_path)),
                ('backdrop2', models.ImageField(upload_to=movie_app.models.backdrop_directory_path)),
                ('running_time', models.IntegerField(help_text='Running time in minutes')),
                ('pg', models.CharField(choices=[('PG', 'PG'), ('G', 'G'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17')])),
                ('tmdb_id', models.CharField(blank=True, max_length=50, null=True)),
                ('hls_playlist', models.FileField(upload_to=movie_app.models.hls_directory_path)),
                ('views', models.IntegerField(default=0)),
                ('actors', models.ManyToManyField(related_name='movies', to='movie_app.actor')),
                ('country', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.country')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.director')),
                ('genres', models.ManyToManyField(related_name='movies', to='movie_app.genre')),
                ('type', models.ForeignKey(default='Movies', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to='movie_app.movietype')),
                ('studio', models.ManyToManyField(related_name='movies', to='movie_app.studio')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_message', models.CharField(blank=True, max_length=100, null=True)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=movie_app.models.user_profile_directory_path)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Femal', 'Femal')])),
                ('date_of_brith', models.DateField(blank=True, null=True)),
                ('membership', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
