# Generated by Django 6.0.1 on 2026-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, default='a', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='qulity',
            field=models.CharField(choices=[('HD', 'HD'), ('CAM', 'CAM')], default='HD'),
        ),
    ]
