# Generated by Django 6.0.1 on 2026-02-20 05:49

import django.db.models.deletion
import movie_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_movie_trailer_url_alter_movie_qulity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100, unique=True)),
                ('file_url', models.FileField(upload_to=movie_app.models.subtitle_directory_path)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movie_app.movie')),
            ],
            options={
                'ordering': ['language'],
            },
        ),
    ]
