# Generated by Django 6.0.1 on 2026-02-20 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_choice', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='subtitle',
            options={'ordering': ['movie']},
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='movie_app.movie'),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitle', to='movie_app.language'),
        ),
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together={('movie', 'language')},
        ),
    ]
