# Generated by Django 6.0.1 on 2026-02-24 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_language_alter_subtitle_options_alter_subtitle_movie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='bunny_embed_code',
            field=models.CharField(default='bunny embed url'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hls_playlist',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, default='youtube url', null=True),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='movie_app.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
