# Generated by Django 6.0.1 on 2026-03-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(default='example:green-land'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')]),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='language_choice',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movietype',
            name='type',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='director',
            unique_together={('first_name', 'last_name')},
        ),
    ]
