# Generated by Django 6.0.1 on 2026-03-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_movie_slug_alter_actor_gender_alter_country_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.CharField(max_length=50),
        ),
    ]
