# Generated by Django 6.0.1 on 2026-03-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0009_alter_movie_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, default='slug', null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_choice',
            field=models.CharField(help_text='Please use lowercase', max_length=50, unique=True),
        ),
    ]
