# Generated by Django 6.0.1 on 2026-03-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_actor_slug_alter_genre_genre_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='slug', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
