# Generated by Django 6.0.1 on 2026-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_studio_slug_alter_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', editable=False, null=True),
        ),
    ]
