# Generated by Django 6.0.1 on 2026-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_alter_actor_slug_alter_studio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='click save to auto generate', null=True),
        ),
    ]
