# Generated by Django 6.0.1 on 2026-03-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_genre_slug_alter_actor_slug_alter_movie_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='tmdb_id',
            field=models.CharField(default='tmdb'),
        ),
    ]
