# Generated by Django 6.0.1 on 2026-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0015_movie_updated_alter_actor_slug_alter_genre_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studio',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
